# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyupm_groveo2', [dirname(__file__)])
        except ImportError:
            import _pyupm_groveo2
            return _pyupm_groveo2
        if fp is not None:
            try:
                _mod = imp.load_module('_pyupm_groveo2', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyupm_groveo2 = swig_import_helper()
    del swig_import_helper
else:
    import _pyupm_groveo2
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class GroveO2(_object):
    """
    API for the Grove O2 Oxygen Gas Sensor.

    ID: groveo2

    Name: Grove O2 Sensor

    Category: gaseous

    Manufacturer: seeed

    Connection: analog  The Grove O2 Oxygen Gas sensor measures the oxygen
    concentration in the air

    C++ includes: groveo2.h 
    """
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GroveO2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GroveO2, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(upm::GroveO2 self, int pin) -> GroveO2

        Parameters:
            pin: int


        GroveO2(int pin)

        Grove O2 Oxygen Gas sensor constructor

        Parameters:
        -----------

        pin:  Analog pin to use 
        """
        this = _pyupm_groveo2.new_GroveO2(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyupm_groveo2.delete_GroveO2
    __del__ = lambda self : None;
    def voltageValue(self):
        """
        voltageValue(GroveO2 self) -> float

        Parameters:
            self: upm::GroveO2 *


        float
        voltageValue()

        Measures O2 from the sensor

        Oxygen concentration as voltage 
        """
        return _pyupm_groveo2.GroveO2_voltageValue(self)

GroveO2_swigregister = _pyupm_groveo2.GroveO2_swigregister
GroveO2_swigregister(GroveO2)

# This file is compatible with both classic and new-style classes.


