# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyupm_bme280', [dirname(__file__)])
        except ImportError:
            import _pyupm_bme280
            return _pyupm_bme280
        if fp is not None:
            try:
                _mod = imp.load_module('_pyupm_bme280', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyupm_bme280 = swig_import_helper()
    del swig_import_helper
else:
    import _pyupm_bme280
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


BME280_I2C_ADDRESS1 = _pyupm_bme280.BME280_I2C_ADDRESS1
BME280_I2C_ADDRESS2 = _pyupm_bme280.BME280_I2C_ADDRESS2
BME280_ONE_U8X = _pyupm_bme280.BME280_ONE_U8X
class BME280(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BME280, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BME280, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _pyupm_bme280.new_BME280(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pyupm_bme280.delete_BME280
    __del__ = lambda self : None;
    def getTemperatureRaw(self): return _pyupm_bme280.BME280_getTemperatureRaw(self)
    def getTemperatureCelcius(self): return _pyupm_bme280.BME280_getTemperatureCelcius(self)
    def getHumidityRaw(self): return _pyupm_bme280.BME280_getHumidityRaw(self)
    def getHumidityRelative(self): return _pyupm_bme280.BME280_getHumidityRelative(self)
    def getModuleName(self): return _pyupm_bme280.BME280_getModuleName(self)
    def getPressureRaw(self): return _pyupm_bme280.BME280_getPressureRaw(self)
    def getPressurePa(self): return _pyupm_bme280.BME280_getPressurePa(self)
    def getTemperatureInternal(self): return _pyupm_bme280.BME280_getTemperatureInternal(self)
    def getPressureInternal(self): return _pyupm_bme280.BME280_getPressureInternal(self)
    def getHumidityInternal(self): return _pyupm_bme280.BME280_getHumidityInternal(self)
    def getTemperatureRawInternal(self): return _pyupm_bme280.BME280_getTemperatureRawInternal(self)
    def getPressureRawInternal(self): return _pyupm_bme280.BME280_getPressureRawInternal(self)
    def getHumidityRawInternal(self): return _pyupm_bme280.BME280_getHumidityRawInternal(self)
    def isAvailable(self): return _pyupm_bme280.BME280_isAvailable(self)
BME280_swigregister = _pyupm_bme280.BME280_swigregister
BME280_swigregister(BME280)

# This file is compatible with both classic and new-style classes.


